artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_dir: data/raw            # Kaggle dataset extracted here
  train_dir: artifacts/data_ingestion/train
  test_dir: artifacts/data_ingestion/test
  test_size: 0.2
  random_state: 42

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/train
  schema_file: schema.yaml
  status_file: artifacts/data_validation/status.txt
  min_images_per_class: 100
